apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"rsolv-platform"},"name":"rsolv-platform","namespace":"rsolv-production"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"rsolv-platform","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"rsolv-platform","app.kubernetes.io/part-of":"rsolv-platform"}},"template":{"metadata":{"labels":{"app":"rsolv-platform","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"rsolv-platform","app.kubernetes.io/part-of":"rsolv-platform","environment":"production","managed-by":"RSOLV-infrastructure","service":"unified"}},"spec":{"containers":[{"env":[{"name":"PORT","value":"4000"},{"name":"API_HOST","value":"api.rsolv.dev"},{"name":"DNS_CLUSTER_QUERY","value":"rsolv-platform-headless.rsolv-production.svc.cluster.local"},{"name":"CLUSTER_SERVICE_NAME","value":"rsolv-platform-headless"},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}},{"name":"LIVE_VIEW_SALT","valueFrom":{"secretKeyRef":{"key":"live-view-salt","name":"rsolv-secrets"}}},{"name":"SECRET_KEY_BASE","valueFrom":{"secretKeyRef":{"key":"secret-key-base","name":"rsolv-secrets"}}},{"name":"DATABASE_URL","value":"postgres://rsolv:73bbaa27311d8ab5dad0522bb8832e61@10.43.203.125:5432/rsolv_landing_prod?sslmode=disable"},{"name":"POSTMARK_API_KEY","valueFrom":{"secretKeyRef":{"key":"postmark-api-key","name":"rsolv-secrets"}}},{"name":"PHX_HOST","value":"rsolv.dev"}],"envFrom":[{"secretRef":{"name":"rsolv-secrets"}}],"image":"ghcr.io/rsolv-dev/rsolv-platform:production-20250802-122436","livenessProbe":{"httpGet":{"path":"/health","port":4000},"initialDelaySeconds":30,"periodSeconds":10},"name":"rsolv-platform","ports":[{"containerPort":4000,"name":"http"},{"containerPort":4021,"name":"metrics"}],"readinessProbe":{"httpGet":{"path":"/health","port":4000},"initialDelaySeconds":5,"periodSeconds":5},"resources":{"limits":{"cpu":"1000m","memory":"1Gi"},"requests":{"cpu":"200m","memory":"512Mi"}}}],"imagePullSecrets":[{"name":"ghcr-secret"}]}}}}
  creationTimestamp: "2025-08-15T05:50:46Z"
  generation: 10
  labels:
    app: rsolv-platform
  name: rsolv-platform
  namespace: rsolv-production
  resourceVersion: "145697009"
  uid: ee6591f3-bdb8-48b4-9d18-afdb5d5ca382
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rsolv-platform
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: rsolv-platform
      app.kubernetes.io/part-of: rsolv-platform
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rsolv-platform
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: rsolv-platform
        app.kubernetes.io/part-of: rsolv-platform
        environment: production
        managed-by: RSOLV-infrastructure
        service: unified
    spec:
      containers:
      - env:
        - name: PORT
          value: "4000"
        - name: API_HOST
          value: api.rsolv.dev
        - name: DNS_CLUSTER_QUERY
          value: rsolv-platform-headless.rsolv-production.svc.cluster.local
        - name: CLUSTER_SERVICE_NAME
          value: rsolv-platform-headless
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: LIVE_VIEW_SALT
          valueFrom:
            secretKeyRef:
              key: live-view-salt
              name: rsolv-secrets
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              key: secret-key-base
              name: rsolv-secrets
        - name: DATABASE_URL
          value: postgres://rsolv:73bbaa27311d8ab5dad0522bb8832e61@postgres-nfs.default.svc.cluster.local:5432/rsolv_landing_prod?sslmode=disable
        - name: POSTMARK_API_KEY
          valueFrom:
            secretKeyRef:
              key: postmark-api-key
              name: rsolv-secrets
        - name: PHX_HOST
          value: rsolv.dev
        envFrom:
        - secretRef:
            name: rsolv-secrets
        image: ghcr.io/rsolv-dev/rsolv-platform:prod-fix-20250816-093716
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 4000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: rsolv-platform
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP
        - containerPort: 4021
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 4000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghcr-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-08-15T05:50:46Z"
    lastUpdateTime: "2025-08-16T15:39:31Z"
    message: ReplicaSet "rsolv-platform-8478c9d578" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-08-16T22:03:56Z"
    lastUpdateTime: "2025-08-16T22:03:56Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 10
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
