apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: default
type: Opaque
stringData:
  password: "cecbe345ab10dfc4b40148f999b3c8b7"
---
apiVersion: v1
kind: Secret
metadata:
  name: rsolv-api-secrets
  namespace: default
type: Opaque
stringData:
  database-url: "postgres://rsolv:cecbe345ab10dfc4b40148f999b3c8b7@postgres:5432/rsolv_platform_prod"
  secret-key-base: "3d956a57b379d96a0baebec140f8bd6be34daa6861287552efb3321c0f216957a52dc1edba30c1e875fd1f7c1b604b7b89fdccb6a0f119c1765af531ee86ea9d"
  anthropic-api-key: "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"
  openai-api-key: "sk-proj-SIUE5GXuwVbM4ZwxFsfTT3BlbkFJEkiAwLAwxiherza3UEdR"
  openrouter-api-key: ""
  sendgrid-api-key: "dummy-sendgrid-key"
  live-view-salt: "2a3be4d55214c3a238fdfe9105b817fff9acbf4957dd5f93bf59ee83833db2a5"
