apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: default
type: Opaque
stringData:
  password: "73bbaa27311d8ab5dad0522bb8832e61"
---
apiVersion: v1
kind: Secret
metadata:
  name: rsolv-api-secrets
  namespace: default
type: Opaque
stringData:
  database-url: "postgres://rsolv:73bbaa27311d8ab5dad0522bb8832e61@postgres:5432/rsolv_api_prod"
  secret-key-base: "ec39e49b32425bd13b7806db426e81430daf92bd419f9f468ed8db04825167c579dfe3a909b3b0c58d13756741ed477805b75825962300e7bcd58d19df0b8eeb"
  anthropic-api-key: "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"
  openai-api-key: "mock-openai-key"
  openrouter-api-key: ""
  postmark-api-key: "82dfc287-055a-4e27-a8f2-3f7c412a1f89"
  live-view-salt: "59ec7fce52f0b1d5bc1851f170eabdb44c161d446fb1e7536a77f2b9992c6003"
